project:
  type: book
  output-dir: _book

book:
  title: "Cheatsheets"
  search: true
  sidebar:
    style: docked
    background: light
  
  chapters:
    - index.qmd
    
    - markdown.qmd
    - git.qmd
    
    - part: "R"
      chapters:
        - import-r.qmd
        - tidy-r.qmd
        - transform-r.qmd
        - visualise-r.qmd
        - packages-r.qmd
      
    - part: "Python"
      chapters: 
        - environments-py.qmd
        - eda-py.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true    

editor: visual

