---
title: "Virtual environments"
---

## Windows

### conda

1. Open **Anaconda Prompt**
2. Create a `conda` environment (with Python version)   
`conda create -n dev python=3.8`
3. List all the available environments    
`conda env list`
5. Activate the environment    
`conda activate dev`   
6. Install `pip` (Package Installer for Python)        
`conda install pip`
7. Install `ipykernel` to use Jupyter notebooks     
`(dev)>pip install ipykernel`
8. Point Jupyter to the new kernel   
`ipython kernel install --name=dev`
9. Open VS Code click Select Interpreter. Then choose 'Python 3.13.0 ('dev') ~\Anaconda3\envs\dev\python.exe'
10. Install necessary packages     
e.g. `pip install pandas`    

To create a list of packages used in a project:    
`pip freeze > requirements.txt`

---
 
Deactivate the environment    
`conda deactivate`    
Delete an environment      
`conda remove -n dev --all`     

### venv

1. Open **Anaconda Prompt**
2. Navigate to project directory   
`cd path/to/folder`
3. Create a `venv` environment    
`python -m venv .venv`
4. Check folder has been created    
`dir`
5. Activate the environment    
`.venv\Scripts\activate`

---

Deactivate the environment
`deactivate`


## Mac

1. Open Terminal and install Python using Homebrew   
```
brew --version
brew install python3
python --version
```
2. Open VS Code and install Python extension    
3. Create a virtual environment  
   - Use Command Palette `(Ctrl+Shift+P)` and **Python: Create Environment**   
   - Select **venv** and choose latest Python interpreter
4. Refresh terminal and add packages    
`pip install pandas`
