---
title: "Further resources"
---

## RAP basics

-   [RAP Companion](https://ukgovdatascience.github.io/rap_companion/) by Matthew Gregory and Matthew Upson
-   [NHS RAP Community of Practice](https://nhsdigital.github.io/rap-community-of-practice/) - guidance on implementing RAP that is aimed at NHS Digital staff.
-   [Reproducible Analytical Pipelines (RAP)](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/) by UK Government Analysis Function
-   [Duck Book](https://best-practice-and-impact.github.io/qa-of-code-guidance/intro.html) - UK Government Analysis Function guidance on the quality assurance of code for analysis and research (QACAR)
-   [RAP Minimum Viable Product](https://github.com/best-practice-and-impact/rap_mvp_maturity_guidance/blob/master/Reproducible-Analytical-Pipelines-MVP.md) - guidance developed by the RAP Champions network
-   [Building reproducible analytical pipelines with R](https://raps-with-r.dev/) - book by Bruno Rodrigues
-   [Building Reproducible Analytical Pipelines](https://rap4mads.eu/) - course by Bruno Rodrigues

## History of RAP

-   [Reproducible Analytical Pipelines](https://dataingovernment.blog.gov.uk/2017/03/27/reproducible-analytical-pipeline/). The original post on RAP by Matt Upson.
-   [Why Government needs sustainable software too](https://www.software.ac.uk/blog/why-government-needs-sustainable-software-too) by Matt Upson
-   [DCMS Sectors Economic Estimates](https://github.com/DCMSstats/eesectors) - The first RAP

## Version control

-   [Data Version Control for Reproducible Analytical Pipelines](https://medium.com/mantisnlp/data-version-control-for-reproducible-analytical-pipelines-5255782d355d) by Matt Upson

## Quality Assurance

-   [Code review for statisticians, data scientists & modellers](https://jcken95.github.io/projects/code_review.html#why-do-we-review-code)

## Packages and templates

-   [govcookiecutter](https://github.com/ukgovdatascience/govcookiecutter) - template for data science projects within the public sector
-   [gptables](https://github.com/best-practice-and-impact/gptables/) - R package for writing consistently formatted statistical tables to Excel
-   [govdown](https://ukgovdatascience.github.io/govdown/index.html) - R package for writing R Markdown documents with gov.uk formatting
-   [DHSC quarto templates](https://github.com/DataS-DHSC/dhsc_quarto_template)

## RAP Plans

-   [Departmental Reproducible Analytical Pipelines (RAP) plans](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/departmental-rap-plans/)

## Case studies

-   [Reproducible Analytical Pipelines: How we saved 3 analysts 6 weeks of copying and pasting](https://blogs.gov.scot/statistics/2023/07/24/reproducible-analytical-pipelines-how-we-saved-3-analysts-6-weeks-of-copying-and-pasting/)
-   [Transforming energy data pipelines](https://analysisfunction.civilservice.gov.uk/blog/transforming-energy-data-pipelines/)
-   [Baltimore City’s Capital Improvement Program Report](https://elipousson.github.io/presentation-tugis2024)
-   [Using Code to Automatically Style Charts for Publications](https://digitalanddata.blog.gov.wales/2024/04/30/using-code-to-automatically-style-charts-for-publications/)

## Further materials

-   [UK Government Analysis Function learning pathway](https://www.gov.uk/guidance/pathways-reproducible-analytical-pipelines)
-   [Reproducible Analytical Pipelines (RAP) using R](https://www.udemy.com/course/reproducible-analytical-pipelines/). MOOC by Matthew Gregory.

## Other

-   [UK Government Service Standard](https://www.gov.uk/service-manual/service-standard). Guidance on open sourcing, user needs and agile project management.
-   [Mentoring a Successful RAP Project](https://dataingovernment.blog.gov.uk/2022/08/08/mentoring-a-successful-rap-project/)
-   [Patterns and anti-patterns of data analysis reuse](https://www.milesmcbain.com/posts/data-analysis-reuse/)
